apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db-server
  name: db-server
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: db-server
---
apiVersion: v1
kind: Pod
metadata:
  name: db-server
  labels:
    io.kompose.service: db-server    
spec:
  restartPolicy: Always
  containers:
    - image: mysql:5.7.8
      name: db-server
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "petclinic"
      - name: MYSQL_DATABASE
        value: "petclinic"
      - name: MYSQL_USER
        value: "clarusway"
      - name: MYSQL_PASSWORD
        value: Clarusway_1
  #     volumeMounts:
  #     - name: db-server
  #       mountPath: /var/lib/mysql
  # volumes:
  # - name: db-server
  #   hostPath:
  #     path: /home/docker/db-petclinic

