apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  template:
    metadata:
      labels:
        io.kompose.service: discovery-server
    spec:
      containers:
        - image: jamesclarusway/petclinic-discovery-server
          name: discovery-server
          ports:
            - containerPort: 8761
          imagePullPolicy: IfNotPresent
          resources: {}
      # for discovery server
      initContainers:
      - name: init-config-server
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z config-server:8888; do echo waiting for config-server; sleep 2; done;']
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
